### ISSUE TITLE
Subir Curriculum Vitae Personal Formato PDF

### ISSUE THREAD

**Issue by jonjonathanarias** [jonjonathanarias/programador2022#14]
En la rama personal agregar su Curriculum Vitae (un archivo en formato .pdf) usando los comandos que hemos aprendido.
Subir la rama personal al repositorio remoto.

**Comment by gabrielbustos23** [comment]
[Curriculum.pdf](https://github.com/jonjonathanarias/programador2022/files/8988081/Curriculum.pdf)

**Comment by Belucacciamani** [comment]
Hola equipo. Ya subí mi curriculum a mi rama personal. Y lo agrego también en este lugar. Saludos!
[Currículum vitae belu.pdf](https://github.com/jonjonathanarias/programador2022/files/9035566/Curriculum.vitae.belu.pdf)
