### ISSUE TITLE
Extraer conceptos generales de Historia y Evolución de bases de Datos a partir de la década del 70

### ISSUE THREAD

**Issue by jonjonathanarias** [jonjonathanarias/programador2022#2]
#Tomar los conceptos mas destacados desarrollados en el siguiente video: https://www.youtube.com/watch?v=JiRjwMlTs84 Clase de Alejandro Mainero

**Comment by josecolombotk** [comment]
[Historia y Evolución de bases de Datos a partir de la década del 70.pdf](https://github.com/jonjonathanarias/programador2022/files/8818884/Historia.y.Evolucion.de.bases.de.Datos.a.partir.de.la.decada.del.70.pdf)

**Comment by josecolombotk** [comment]
para revisar
