### ISSUE TITLE
Extraer los conceptos Principales  de Ética y Deontología

### ISSUE THREAD

**Issue by jonjonathanarias** [jonjonathanarias/programador2022#3]
#Extraer los conceptos Principales  de Ética y Deontología: Definición, . Objetivos de la EI (Ética Informática), LA DEONTOLOGÍA – LA DEONTOLOGÍA INFORMÁTICA, LOS CÓDIGOS ÉTICOS.
##Utilizar el material bibliográfico siguiente: ###https://acceso.ispc.edu.ar/pluginfile.php/51705/mod_book/chapter/805/%C3%89tica%20y%20deontolog%C3%ADa%20inform%C3%A1tica%20conceptos%20b%C3%A1sicos.pdf?time=1651198880124

**Comment by gabrielbustos23** [comment]
[Tarea Github.docx](https://github.com/jonjonathanarias/programador2022/files/8988058/Tarea.Github.docx)
