### ISSUE TITLE
Realizar un breve resumen de los Componentes de los Sistemas Gestores de Bases de Datos 

### ISSUE THREAD

**Issue by jonjonathanarias** [jonjonathanarias/programador2022#4]
#Exponer los Principales componentes de los SGBD: Lenguajes de los SGBD y como se clasifican, Recursos humanos de las bases de datos, ¿Qué es Estructura multicapa?, hacer un breve tipiado del Funcionamiento del SGBD.  
##utilizar el siguiente material bibliográfico: 
###https://acceso.ispc.edu.ar/pluginfile.php/51710/mod_book/chapter/1779/03%20-%20Sistemas%20Gestores%20de%20Bases%20de%20Datos%20-%20Estructura%20interna.pdf

**Comment by andreslmd** [comment]
A revisar!

**Comment by andreslmd** [comment]
[Sistemas Gestores de Bases de Datos.pdf](https://github.com/jonjonathanarias/programador2022/files/8886246/Sistemas.Gestores.de.Bases.de.Datos.pdf)
