### ISSUE TITLE
Realizr un breve resumen de Dilema en las Redes Sociales

### ISSUE THREAD

**Issue by jonjonathanarias** [jonjonathanarias/programador2022#5]
#exponer los conceptos mas generales: Herramientas diseñadas para engancharnos y manipularnos, Seguridad vs Inseguridad, Consejos para protegerse
## utilizar el siguiente material bibliográfico:
###https://acceso.ispc.edu.ar/pluginfile.php/51705/mod_book/chapter/815/Dilema%20en%20las%20redes%20sociales.pdf

**Comment by PameAquino13** [comment]
“Hay dos industrias que llaman a sus clientes usuarios: las drogas ilegales y los software”
El dilema de las redes sociales, aparece en un documental “The Social Dilemma”, se estrenó en febrero del 2020. El films describe las adicciones y los impactos negativos de las redes en las personas y en la comunidad. La manera de atraer a los usuarios es a través  de recomendaciones automáticas, notificaciones  y publicidades sugeridas.
El objetivo de las empresas, organizaciones o políticos es captar el tiempo de las personas para vender productos o ideas dirigida a una audiencia vulnerable e hipersegmentada.
El documental es clasificado como docudrama, la película donde se elogia la manera de detallar las herramientas y estrategias de un lenguaje accesible a la audiencia, pero también recibe críticas al no ofrecer soluciones a los problemas antes planteados, y por ser presentada por personas con características similares a los problemas planteados, muchos de los entrevistados son exejecutivos: con características de ser hombres jóvenes, ricos y blancos.
Ellos consideran que sino pagas por productos el producto eres tú.
En noticias financieras Bloomberg Mark Zuckerberg ganó mucho dinero durante la pandemia, ofreciendo servicios gratuitos y cuanto más tiempo pase el usuario conectado más datos se obtiene sobre: hábitos, gustos y características de consumo.
La manera en Facebook y Google recompilan datos es mediante algoritmos que mapean los me gustas y los comentarios, analizan el tiempo de lectura y la exposición  a las imágenes para alimentar enormes servidores (algunos de ellos alojados en submarinos). Estas empresas ofrecen información sobre los usuarios a los clientes.
Triestan Harris exingeniero de google advierte el riesgo de las adicciones  en los usuarios y muestra la manera que utiliza la empresa para mantener a los usuarios distraídos mientras los anunciantes ganan dinero a través de desplazamiento automático, notificaciones, la dinámica del “me gusta”. Sostiene que las redes sociales capacitan a toda una generación de individuos que cuando se sienten solos o asustados, recurren a los `chupetes digitales´ para calmarse.
Estos chupetes son la validación recibida en elogios, y advierte sobre  la peligrosidad de nuestra capacidad para afrontar las cosas.
El film muestra cómo trabajan profesionales en psicología y tecnología, a través de las falsas recompensas.
Otro testimonio es el aportado por Aza Raskin que es el inventor de desplazamiento infinito utilizado  por la mayoría de sitios web. Guillaume Chaslut uno de los desarrolladores de algoritmo que recomienda videos en YouTube, Bailey Richardson un desarrollador de Instagram. Son quienes dan testimonio de los métodos para manipular las emociones a través de la dopamina, un neurotransmisor relacionado con el placer, la alegría y el bienestar. Mediante “sistemas de recompensa inmediata” como los “me gusta”, los comentarios positivos. Habrían creado métodos de navegación capaz de generar nuevos impulsos artificiales de dopamina, las redes sociales mantiene conectadas a una legión de usuarios cada vez más solitarios y necesitados.
El psicólogo social Jonathan Haidt establece una tendencia relacionada con el aumento de depresión y ansiedad, especialmente en niños y adolescente.
Datos oficiales muestran como segunda causa de muerte en niños escolares de 12 a 18 años, de niñas entre 15 a 19 años, que ha ido en aumento entre los años 2007 al 2015. Esto se debe al a manera irresponsable en que las redes sociales tratan a los usuarios, dentro de ello mencionan como causas a los comentarios descalificativos.
También en el documental aseguran que las noticias falsas rinden más dinero que las verdaderas, porque aseguran que la verdad es aburrida.
Al final, aseguran que una de las maneras de protegerse de la manipulación de las herramientas es: deshabilitar las notificaciones, no acceder a recomendaciones de video o contenidos sin reflexionar sobre ellos, desconectarse una hora antes de dormir, y valorar los clics y tu tiempo porque así es como las redes sociales ganan dinero.

**Comment by GabrielNDJ** [comment]
Hecho por Pamela
